name = "KitDistributed"
uuid = "02e53f8b-c208-4a2b-afcb-3867cbe52f0a"
authors = ["Tianbai Xiao <tianbaixiao@gmail.com>"]
version = "0.1.0"

[deps]
KitBase = "86eed249-3a28-466f-8d3a-596821e1af9a"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"

[compat]
KitBase = "0.9"
MPI = "0.19"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]